### ISSUE TITLE
Menu system doesn't allow you to save existing manual menus

### ISSUE THREAD

**Issue by jfi** [tastybamboo/panda-cms#12]
### Steps to reproduce

```ruby
# Your reproduction script goes here
```

### System configuration

**Rails version**:

**Ruby version**:

**Comment by jadeKing** [comment]
Is this the issue that happens when you try to save a new menu item to an existing 'static' menu, when its set to link to a Page?
`Validation failed: Menu items page must be a valid page or external link, both are set, Menu items external url must be a valid page or external link, both are set`.
I started looking at it previously and I think it was because when you save the Menu form with a Page chosen, it sets the url text_field to an empty string. Then when validation runs its thinks both fields have been filled out. 

If this is not the same problem I will open a new issue.

**Comment by jfi** [comment]
Closing pending rewrite of menu system due to broken dependency on `stimulus-components-rails-nested-form`.
